server:
  port: ${CUSTOM.SERVER.PORT:9020}

#Mongo DB Configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://root:robin123@mongo-service:27017/productdb?authSource=admin}

#Posqre Configuration
jpa:
  databasePlatform:
  hibernate:
    ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

datasource:
  url: ${POSTGRESQL.URL.CONNECTION:jdbc:postgresql://localhost:5432/mitocode_db}
  username: ${POSTGRES.USERNAME:postgres}
  password: ${POSTGRES.PASSWORD:robin123}