server:
  port: ${CUSTOM.SERVER.PORT:9020}

#Mongo DB Configuration mongo-service
spring:
  data:
    mongodb:
      uri: mongodb://root:robin123@localhost:27017/productdb?authSource=admin
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/mitocode_db
    username: ${POSTGRES.USERNAME:postgres}
    password: ${POSTGRES.PASSWORD:robin123}